apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: invoiceshelf
resources:
  - check-estimates-status.cronjob.yaml
  - check-invoice-status.cronjob.yaml
  - statefulset.yaml
  - service.yaml
images:
  - name: invoiceshelf/invoiceshelf
    newTag: 1.2.2@sha256:6f735cd602eb8005353e1e8963a5b584fe94c2206aaf99bc5269821a7b30df53
