apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-invoice-status
  labels:
    app.kubernetes.io/name: check-invoice-status
    app.kubernetes.io/component: cron
spec:
  # Every 10 minutes
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: check-invoice-status
            image: invoiceshelf/invoiceshelf
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: cron-env
            command:
              - php
              - artisan
              - check:invoices:status
          restartPolicy: OnFailure
