apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-app
  labels:
    app.kubernetes.io/name: crater-app
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: crater-app
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crater-app
        app.kubernetes.io/component: server
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: crater-app
          image: drgrovellc/crater-app
          ports:
            - name: fastcgi
              containerPort: 9000
          securityContext:
            allowPrivilegeEscalation: false
