apiVersion: v1
kind: Service
metadata:
  name: invoiceshelf
  labels:
    app.kubernetes.io/name: invoiceshelf
    app.kubernetes.io/part-of: invoiceshelf
spec:
  selector:
    app.kubernetes.io/name: invoiceshelf
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 80
      targetPort: 80
