apiVersion: v1
kind: Service
metadata:
  name: crater-app
  labels:
    app.kubernetes.io/name: crater-app
    app.kubernetes.io/part-of: crater-app
spec:
  selector:
    app.kubernetes.io/name: crater-app
    app.kubernetes.io/component: server
  ports:
    - name: fastcgi
      port: 9000
      targetPort: 9000
